controller:
  imagePullSecretName: regcred
  connectK8SController:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: ghcr.io/nokia-eda/eda-connect-k8s-controller
      tag: 4.0.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
  serviceAccount:
    annotations: {}
controllerEnvConfig:
  connectpluginname: k8s-controller-plugin
  heartbeat: "10"
  loglevel: info
  namespace: default
  skiptlsverify: "false"
  tlscertificatedata: ""
  tlsenabled: "true"
controllerEnvSecret:
  connectHost: ""
  connectPassword: ""
  connectUsername: ""
controllerMetricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
kubernetesClusterDomain: cluster.local
