apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eda-connect-k8s.fullname" . }}-controller-env-secret
  labels:
  {{- include "eda-connect-k8s.labels" . | nindent 4 }}
data:
  CONNECT_HOST: {{ required "controllerEnvSecret.connectHost is required" .Values.controllerEnvSecret.connectHost
    | b64enc | quote }}
  CONNECT_PASSWORD: {{ required "controllerEnvSecret.connectPassword is required"
    .Values.controllerEnvSecret.connectPassword | b64enc | quote }}
  CONNECT_USERNAME: {{ required "controllerEnvSecret.connectUsername is required"
    .Values.controllerEnvSecret.connectUsername | b64enc | quote }}
type: Opaque