apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eda-connect-k8s.fullname" . }}-manager-role
  labels:
  {{- include "eda-connect-k8s.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - connect.eda.nokia.com
  resources:
  - connectnetworkattachmentstatuses
  - connectnetworkdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - connect.eda.nokia.com
  resources:
  - connectnetworkattachmentstatuses/status
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - connect.eda.nokia.com
  resources:
  - connectnetworkdefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - connect.eda.nokia.com
  resources:
  - connectnetworkdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nmstate.io
  resources:
  - nodenetworkstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nmstate.io
  resources:
  - nodenetworkstates/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eda-connect-k8s.fullname" . }}-manager-rolebinding
  labels:
    eda.nokia.com/app: connect-k8s-controller
    eda.nokia.com/app-group: connect
  {{- include "eda-connect-k8s.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "eda-connect-k8s.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "eda-connect-k8s.fullname" . }}-controller'
  namespace: '{{ .Release.Namespace }}'