apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eda-connect-k8s.fullname" . }}-proxy-role
  labels:
    eda.nokia.com/app: connect-k8s-controller
    eda.nokia.com/app-group: connect
  {{- include "eda-connect-k8s.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eda-connect-k8s.fullname" . }}-proxy-rolebinding
  labels:
    eda.nokia.com/app: connect-k8s-controller
    eda.nokia.com/app-group: connect
  {{- include "eda-connect-k8s.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "eda-connect-k8s.fullname" . }}-proxy-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "eda-connect-k8s.fullname" . }}-controller'
  namespace: '{{ .Release.Namespace }}'