apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eda-connect-k8s.fullname" . }}-controller
  labels:
    eda.nokia.com/app: connect-k8s-controller
    eda.nokia.com/app-group: connect
  {{- include "eda-connect-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}